import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.162.0/build/three.module.js';

const fixes=document.createElement('style');fixes.textContent='.type-picker{grid-template-columns:repeat(3,1fr)}.custom-color{width:32px;height:32px;margin:0!important;border-radius:50%;overflow:hidden;border:1px solid #999;cursor:pointer}.custom-color input{width:46px;height:46px;padding:0;margin:-7px!important;border:0;background:transparent;cursor:pointer}.custom-label{align-self:center;font-size:.75rem;font-weight:700}';document.head.append(fixes);

const box=document.querySelector('#three-canvas'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;box.append(renderer.domElement);camera.position.set(0,1.1,6);scene.add(new THREE.HemisphereLight(0xffffff,0x453c38,2.6));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(4,5,4);scene.add(key);const floor=new THREE.Mesh(new THREE.CircleGeometry(2.7,64),new THREE.ShadowMaterial({opacity:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.48;scene.add(floor);
let color='#f7f2e9',type='mug',uploaded=null,product,dragging=false,lastX=0,lastY=0;const printCanvas=document.createElement('canvas'),printCtx=printCanvas.getContext('2d');printCanvas.width=1200;printCanvas.height=900;const printTexture=new THREE.CanvasTexture(printCanvas);printTexture.colorSpace=THREE.SRGBColorSpace;printTexture.minFilter=THREE.LinearFilter;
function contrast(hex){const c=hex.slice(1),r=parseInt(c.slice(0,2),16),g=parseInt(c.slice(2,4),16),b=parseInt(c.slice(4,6),16);return(r*299+g*587+b*114)/1000>155?'#29213e':'#fff'}
function wrapped(text,x,y,maxWidth,lineHeight){const words=text.split(' '),lines=[];let line='';for(const word of words){const candidate=line?line+' '+word:word;if(printCtx.measureText(candidate).width>maxWidth&&line){lines.push(line);line=word}else line=candidate}lines.push(line);lines.forEach((row,index)=>printCtx.fillText(row,x,y+(index-(lines.length-1)/2)*lineHeight))}
function drawPrint(){printCtx.clearRect(0,0,1200,900);const text=document.querySelector('#custom-text').value.trim();if(uploaded){const scale=Math.min(470/uploaded.width,470/uploaded.height),w=uploaded.width*scale,h=uploaded.height*scale;printCtx.drawImage(uploaded,(1200-w)/2,180,w,h)}if(text){printCtx.fillStyle=contrast(color);printCtx.font='800 78px Outfit,Arial';printCtx.textAlign='center';printCtx.textBaseline='middle';wrapped(text,600,uploaded?710:450,960,88)}printTexture.needsUpdate=true}
function printBand(radius,height){return new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,height,72,1,true,.52,2.1),new THREE.MeshBasicMaterial({map:printTexture,transparent:true,depthWrite:false,side:THREE.DoubleSide}))}
function shirtShape(){const s=new THREE.Shape();s.moveTo(-1,-1.35);s.lineTo(-1,.72);s.lineTo(-1.55,1.05);s.lineTo(-1.15,1.55);s.lineTo(-.58,1.2);s.quadraticCurveTo(0,1.45,.58,1.2);s.lineTo(1.15,1.55);s.lineTo(1.55,1.05);s.lineTo(1,.72);s.lineTo(1,-1.35);s.closePath();return s}
function dispose(){if(!product)return;scene.remove(product);product.traverse(x=>{x.geometry?.dispose();x.material?.dispose()})}
function build(){dispose();drawPrint();product=new THREE.Group();const solid=new THREE.MeshStandardMaterial({color,roughness:.34,metalness:.04});if(type==='mug'){product.add(new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.03,2.4,96),solid),printBand(1.211,2.15));const rim=new THREE.Mesh(new THREE.TorusGeometry(1.2,.06,16,80),solid);rim.rotation.x=Math.PI/2;rim.position.y=1.2;product.add(rim);const handle=new THREE.Mesh(new THREE.TorusGeometry(.58,.15,20,50,Math.PI),solid);handle.rotation.z=-Math.PI/2;handle.position.set(1.12,.1,0);product.add(handle)}else if(type==='glass'){const glass=new THREE.MeshPhysicalMaterial({color,roughness:.14,metalness:.03,transparent:true,opacity:.85,transmission:.16,side:THREE.DoubleSide});product.add(new THREE.Mesh(new THREE.CylinderGeometry(1.02,.9,2.85,96,1,true),glass),printBand(1.035,2.7));const base=new THREE.Mesh(new THREE.CylinderGeometry(.92,.92,.08,96),solid);base.position.y=-1.42;product.add(base);const rim=new THREE.Mesh(new THREE.TorusGeometry(1.02,.035,12,80),solid);rim.rotation.x=Math.PI/2;rim.position.y=1.42;product.add(rim)}else{const body=new THREE.Mesh(new THREE.ExtrudeGeometry(shirtShape(),{depth:.13,bevelEnabled:true,bevelThickness:.03,bevelSize:.03,bevelSegments:2}),solid);body.position.z=-.07;product.add(body);const print=new THREE.Mesh(new THREE.PlaneGeometry(1.5,1.5),new THREE.MeshBasicMaterial({map:printTexture,transparent:true,depthWrite:false}));print.position.set(0,.1,.08);product.add(print)}product.rotation.y=-.5;scene.add(product)}
function resize(){const w=box.clientWidth,h=box.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(box);function animate(){requestAnimationFrame(animate);renderer.render(scene,camera)}
renderer.domElement.addEventListener('pointerdown',event=>{dragging=true;lastX=event.clientX;lastY=event.clientY;renderer.domElement.setPointerCapture(event.pointerId)});renderer.domElement.addEventListener('pointermove',event=>{if(!dragging||!product)return;product.rotation.y+=(event.clientX-lastX)*.012;product.rotation.x+=((event.clientY-lastY)*.006);product.rotation.x=Math.max(-.5,Math.min(.5,product.rotation.x));lastX=event.clientX;lastY=event.clientY});renderer.domElement.addEventListener('pointerup',()=>dragging=false);renderer.domElement.addEventListener('wheel',event=>{camera.position.z=Math.max(3,Math.min(8,camera.position.z+event.deltaY*.006));event.preventDefault()},{passive:false});
document.querySelectorAll('.type').forEach(button=>button.onclick=()=>{document.querySelectorAll('.type').forEach(x=>x.classList.remove('active'));button.classList.add('active');type=button.dataset.type;build()});document.querySelector('#custom-text').oninput=drawPrint;document.querySelector('#color-picker').onclick=event=>{const button=event.target.closest('.color');if(!button)return;document.querySelectorAll('.color').forEach(x=>x.classList.remove('active'));button.classList.add('active');color=button.dataset.color;document.querySelector('#custom-color').value=color;build()};document.querySelector('#custom-color').oninput=event=>{color=event.target.value;document.querySelectorAll('.color').forEach(x=>x.classList.remove('active'));build()};document.querySelector('#custom-image').onchange=event=>{const file=event.target.files[0];if(!file)return;const image=new Image();image.onload=()=>{uploaded=image;drawPrint()};image.src=URL.createObjectURL(file)};document.querySelector('#send-design').onclick=()=>{const phrase=document.querySelector('#custom-text').value.trim()||'Sin frase',piece={mug:'taza',glass:'vaso',shirt:'playera'}[type],message=`Hola, quiero cotizar una ${piece} personalizada.\n\nColor: ${color}\nFrase: ${phrase}\nImagen/logo: ${uploaded?'Sí (la enviaré aquí)':'No'}`;window.open(`https://wa.me/5210000000000?text=${encodeURIComponent(message)}`,'_blank','noopener')};
build();resize();animate();
